### ISSUE TITLE
Add environment to metadata

### ISSUE THREAD

**Issue by MatthewKhouzam** [dorsal-lab/rocprofiler_ctf_plugin#2]
Allow versioning of traces

**Comment by yoann-heitz** [comment]
The ROCm version is now added to the metadata file when regenerating barectf files. For the ROCm-4.5.x branch, the default ROCm version is 4.5.0 in the metadata file.
I am keeping the issue open since we are also working on defining version numbers for the plugin (distinct from the ROCm version).

**Comment by yoann-heitz** [comment]
Added a plugin version number (in addition to the ROCm version) in the metadata file, starting from branch rocm-5.0.x (the branches are correlated with plugin version).
