### ISSUE TITLE
Post processing error with Python < 3.7

### ISSUE THREAD

**Issue by arfio** [dorsal-lab/rocprofiler_ctf_plugin#3]
time.clock_gettime_ns() is not available in python versions < 3.7.

**Comment by yoann-heitz** [comment]
The post processing was converted in C++ with 2017 specifications. 
Starting from the rocm-5.0.x branch (correlated with the plugin versions), the post processing does not rely on a specific version of Python. However you need to have clang 5+ to have the 2017 specifications implemented.
